name: Build&Release

on:
  push:
    tags:
    - 'v*'
    - '*-rc'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o dist/ proxyservice.go
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: proxyservice
        path: target/release/proxyservice
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: target/release/proxyservice
